### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by lightonflux** [andris9/mailtrain#19]
What's planned in regard to translation? I didn't see anything on the roadmap. 

I would prefer it when the project integrated with a service like transifex so people without or very little code and git knowledge can easily contribute. 

Transifex is gratis for open source projects. And it is pretty easy to integrate and more importantly easy to use.

[Guide for github](http://docs.transifex.com/integrations/github/)

**Comment by bago** [comment]
+1
For mosaico we're using Transifex and I have to say it works fine.
https://github.com/voidlabs/mosaico/tree/master/res/lang

The good think in Transifex is that the translation can be collaborative and when you add new string translators will be able to easily see what they need to complete.

**Comment by andris9** [comment]
Generally, as I'm not an native english speaker either, I support adding translations. At this point though it would mean too much work as the code and strings change all the time. I would defer this until there's some actual stability reached.

**Comment by witzig** [comment]
Ten months later, has actual stability been reached? At minimum, I need to translate the templates in views/emails. @andris9 what's your call? i18n-node?

**Comment by andris9** [comment]
Translation support now exists

**Comment by lightonflux** [comment]
@andris9 how does one translate the project? 

Do i just copy the .po file and start translating or do you plan to integrate the project in a service like transifex. Which is very handy because you can notify your translators, when you prepare a new release.

**Comment by witzig** [comment]
@lightonflux, see: https://github.com/andris9/mailtrain/blob/master/README.md#translations

In case you need german translation, I'm 90% done.

**Comment by lightonflux** [comment]
Thanks.

> I'm 90% done.

Nice. Looking forward to test it!

**Comment by witzig** [comment]
@lightonflux, de_DE is in master now.

It would be great if you could polish it up a bit, since Hochdeutsch isn't my native language. :)

**Comment by lightonflux** [comment]
Tried to use it with the docker setup by changing the language key to "de". But when starting with docker-compose i only get EN. :(

**Comment by saschafoerster** [comment]
I ready to help with the german translation. But I need somehow to get it working with docker as well. I tried all the options. I think I should only change the setting in production.toml to 
>language="de_DE"
then, docker-composer build and start again, no?

**Comment by mailanetworks** [comment]
This is correct!
I´m finishing up Brazilian Portuguese pt_BR and French FR.

Thanks,

**Comment by saschafoerster** [comment]
https://news.bonn.digital But why does it keep showing the english version of it? Is there a way to debug the options in docker?

**Comment by mailanetworks** [comment]
Oh I see, maybe Docker uses a template, in this case you would need to modify the template. I´ll install a docker version and see how it goes.

Thanks,

**Comment by saschafoerster** [comment]
I found the solution (not well documented, I guess): 

I had to change some things in docker-compose.override.yml, so it doesn't need to copy files from the server into docker, but uses the folders directly, where I can make changes, which get into effect with the next rebuild. I am not shure, what will happen, when I download a fresh copy via git, but I hope that .gitignore will work well and not overwrite my changes.

```
version: '2'
services:
  mysql:
    restart: always
  redis:
    restart: always
  mailtrain:
    build: ./
    volumes:
      - "/home/mailtrain/config/production.toml:/app/config/production.toml"
      - "/home/mailtrain/languages/de_DE_bonndigital.mo:/app/languages/de_DE_bonndigital.mo"
      - "/home/mailtrain/languages/de_DE_bonndigital.po:/app/languages/de_DE_bonndigital.po"
    ports:
      - "3000:3000"
    restart: always

```
